# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  cuf-registration-app-service:
    image: cuf-registration-app-service
    build:
      context: .
      dockerfile: cuf-registration-app-service/Dockerfile
    ports:
      - 8080:8080
